source_docs/css/proj_docs.css

全体的に暗くて見づらかったため、公式サイトの色味とフォントを参考に変えてみました。

見易さのため全体的な色とフォントを変更

---

.circleci/deploy.sh

自動commit & pushの必要がないときにCircleCIがfailしていたのを修正

CircleCIのdeployを修正

---

.gitignore

.gitignoreにdub testで生成されるファイルを追加

---

source/uda_example.d

UDAの活用例を追加

---

source/regex_example.d

正規表現のexampleを追加

---

source/uda_example.d

Twitterで投げられていた質問の回答です。
https://twitter.com/knzk_work/status/1170225885447897093

関数パラメーターのUDA取得方法を追加

---

source/process_example.d

プロセス操作の例(Posix)を追加

---

ddoc/main.ddoc
source_docs/css/proj_docs.css

作業中ですが、ざっくりスマホでも見れるようにレイアウト調整しました。
レスポンシブなデザインとして幅が768pxを境に見た目が変わるようにしたので、手元でビルドしてウィンドウサイズを調整すれば見れると思います。
あとはChromeの開発者ツールで端末エミュレートするとそれっぽい感じになります。
コードがはみ出たりURLが横にあふれたりしているので考えることがまだいくつかある状態です。

スマホ向けのレイアウト調整

---

source/meta_example.d

メタプログラミング関連でis式やUDAなど特別なトピックに分類が難しいものを書くところを作れればと思います。

Add meta_example

---

source/exception_example.d

一気に全部は出すのはレビューも重くなるので、一旦ここまでの内容で。

例外の導入部分を作成

---

source/parallelism_example.d

大きく3つ追加しました！
- parallel と synchronized を使った簡単な同期の例
- taskを使った処理の定義と実行と待機
- TaskPoolの作成と parallel/put の利用
#29 の一部になると思うので、そのあたり少し整理します。

std.parallelismの例を追加

---

source/process_example.d

Windowsでの事例を追加

---

source/typecons_example.d

Rebindableの例を追加した。

---

README.md

レビューポイントの追記

---

source/sync_example.d

排他および同期処理の例を追加

---

source/data/package.d
source/data/zip_example.d

ZIPファイルの例を追加

---

source/container_example.d

スタックとキューの例を追加

---

source/meta_example.d

TemplateArgsOfとTemplateOfの例を追加

---

source/data/base64_example.d
source/data/package.d

Base64の例を追加

---

source/sumtype_example.d

SumTypeの例を追加

---

thirdparty/libdparse/dub.sdl
thirdparty/libdparse/source/libdparse_usage/example.d

libdparse 0.19.2で修正されたので戻します。
fixes #157

Revert "issue #157 libdparseのエラー回避"

---

thirdparty/vibe-d/source/vibed_usage/_common.d
thirdparty/vibe-d/source/vibed_usage/auth.d

認証とか権限とかセッションについて説明するページが必要かなと思って作りました。

vibe.dを使った認証の追加

---

source/data/json_example.d

浮動小数点型の扱いを追加

---

source/gc_example.d

関連 issue #19 
`GC.disable`・`GC.disable`・`GC.minimize`等の例を追加しました。

ガベージコレクションの制御の例追加

---

source/exception_example.d

ifThrown, assertThrown, handleの例追加

---

source/string_example.d

文字列置換の例を追加

---

source/hash_example.d

vibe.dのサンプルでstd.digestを色々使うケースがあるようなので、一番基本的なところだけ整理しました。

hash計算のサンプルを追加

---

source/container_example.d

WikiにChatGPTを使ったブロック単位のコードレビューの枠組みを記述しました。
指摘を元に試しにコンテナのサンプルを書き換えてみたので参考までに更新します。
コード書いてもらえることもあるんですが、とてもコードが不足している状況でもない限り結構稀のようです。
次はコード生成する方も何か考えてみますね…

コンテナの説明を整えました
